- name: Download Microsoft package configuration for Ubuntu
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
    dest: /tmp/packages-microsoft-prod.deb

- name: Install Microsoft package configuration
  ansible.builtin.apt:
    deb: /tmp/packages-microsoft-prod.deb
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install required packages for Blobfuse
  ansible.builtin.apt:
    name:
      - fuse3
      - blobfuse2
    state: present
    update_cache: yes

- name: Ensure the directory for mounting Azure Blob storage exists
  ansible.builtin.file:
    path: /mnt/azureblob
    state: directory
    mode: '0750'
  # This task will create the directory if it doesn't exist

- name: Ensure the tmp path for Blobfuse exists
  ansible.builtin.file:
    path: /mnt/resource/blobfusetmp
    state: directory
    mode: '0750'
  # This task ensures that the temporary path exists, which is required for blobfuse

##- name: Create a fuse connection to the Azure Blob storage
##  ansible.builtin.command: >
##    blobfuse /mnt/azureblob --tmp-path=/mnt/resource/blobfusetmp 
##    --container-name={{ container_name }} 
##    --account-name={{ storage_account_name }} 
##    --account-key={{ storage_account_key }} 
##    -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120
##  args:
##    creates: /mnt/azureblob

- name: Verify that Azure Blob storage is mounted
  ansible.builtin.command: df -h /mnt/azureblob
  register: mount_output

- name: Debug output of the mounted Azure Blob storage
  ansible.builtin.debug:
    msg: "{{ mount_output.stdout_lines }}"