---
- name: Assign actual date into a variable
  set_fact:
    actual_date: "{{ ansible_date_time.date | regex_replace('-', '') }}"

- name: Using the created date-var
  ansible.builtin.debug:
    msg: "Actual date to perform the restore is: {{ actual_date }}"

- name: Retrieve MongoDB URI from /etc/pritunl-web.env
  ansible.builtin.command:
    cmd: "grep 'PRITUNL_MONGODB_URI' /etc/pritunl-web.env"
  register: mongodb_uri_result

- name: Extract and set MongoDB URI
  set_fact:
    mongodb_uri: "{{ mongodb_uri_result.stdout | regex_replace('PRITUNL_MONGODB_URI=(.*)', '\\1') }}"

- name: Restore MongoDB backup
  ansible.builtin.shell: "mongorestore --uri=\"{{ mongodb_uri }}\" --archive=/backups/pritunl-backup-{{ actual_date }}.archive"
  register: restore_mongo
