---
- name: Check if blobfuse2 is installed
  ansible.builtin.package_facts:
    manager: "apt"

- name: Install Microsoft package configuration for Ubuntu
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
    dest: /tmp/packages-microsoft-prod.deb
  when: "'blobfuse2' not in ansible_facts.packages"

- name: Install Microsoft package configuration
  ansible.builtin.apt:
    deb: /tmp/packages-microsoft-prod.deb
    state: present
  when: "'blobfuse2' not in ansible_facts.packages"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: "'blobfuse2' not in ansible_facts.packages"

- name: Install required packages for Blobfuse
  ansible.builtin.apt:
    name:
      - fuse3
      - blobfuse2
    state: present
    update_cache: yes
  when: "'blobfuse2' not in ansible_facts.packages"

- name: Ensure the directory for mounting Azure Blob storage exists
  ansible.builtin.file:
    path: /mnt/azureblob
    state: directory
    mode: '0750'

- name: Ensure the tmp path for Blobfuse exists
  ansible.builtin.file:
    path: /mnt/resource/blobfusetmp
    state: directory
    mode: '0750'

- name: Verify if /mnt/azureblob is already mounted
  ansible.builtin.command: "mountpoint /mnt/azureblob"
  register: mountpoint_check
  failed_when: false

- name: Mount Azure Blob storage if not already mounted
  ansible.builtin.command: >
    blobfuse /mnt/azureblob --tmp-path=/mnt/resource/blobfusetmp 
    --container-name={{ container_name }} 
    --account-name={{ storage_account_name }} 
    --account-key={{ storage_account_key }} 
    -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120
  when: mountpoint_check.rc != 0
  args:
    creates: /mnt/azureblob

- name: Verify that Azure Blob storage is mounted
  ansible.builtin.command: df -h /mnt/azureblob
  register: mount_output

- name: Debug output of the mounted Azure Blob storage
  ansible.builtin.debug:
    msg: "{{ mount_output.stdout_lines }}"

- name: Retrieve MongoDB URI from /etc/pritunl-web.env
  ansible.builtin.command:
    cmd: "grep 'PRITUNL_MONGODB_URI' /etc/pritunl-web.env"
  register: mongodb_uri_result

- name: Extract and set MongoDB URI
  set_fact:
    mongodb_uri: "{{ mongodb_uri_result.stdout | regex_replace('PRITUNL_MONGODB_URI=(.*)', '\\1') }}"

- name: Check if backup directory exists
  ansible.builtin.stat:
    path: "/mnt/azureblob/backups"
  register: backup_dir_status

- name: Create backup directory if it does not exist
  ansible.builtin.file:
    path: "/mnt/azureblob/backups"
    state: directory
  when: not backup_dir_status.stat.exists

- name: Find the most recent backup file
  ansible.builtin.shell: "ls -t /backups/pritunl-backup-*.archive | head -n 1"
  register: recent_backup_file

- name: Debug output of the most recent backup file
  ansible.builtin.debug:
    msg: "The most recent backup file is: {{ recent_backup_file.stdout }}"

- name: Restore MongoDB backup from the most recent file
  ansible.builtin.shell: "mongorestore --uri=\"{{ mongodb_uri }}\" --archive={{ recent_backup_file.stdout }}"
  register: restore_mongo
