---
- hosts: all
  become: yes
  vars:
    role_action: "none"  # default value, overridden by --extra-vars
    destination_server: ""  # variable for destination server

  tasks:
    - name: Run Backup Role if selected
      include_role:
        name: backup
      when: role_action == "backup"

    - name: Run Restore Role if selected
      include_role:
        name: restore
      when: role_action == "restore"
