all:
  hosts:
    labnode1:
      ansible_host: 192.168.1.131
    labnode2:
      ansible_host: 192.168.1.132
    labnode3:
      ansible_host: 192.168.1.133
    labnode4:
      ansible_host: 192.168.1.134
    labnode5:
      ansible_host: 192.168.1.135

  children:
    pritunl_servers1:
      hosts:
        labnode1:
        labnode3:
        labnode5:
        
    pritunl_servers2:
      hosts:
        labnode2:
        labnode4:

  vars:
    ansible_user: root        
    ansible_ssh_private_key_file: /home/kloud/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_timeout: 30
