---
- name: Assign actual date into a variable
  set_fact:
    actual_date: "{{ lookup('pipe', 'date +%d%m%Y') }}"

- name: Using the created date-var
  ansible.builtin.debug:
    msg: "Actual date to perform the backup is: {{ actual_date }}"

- name: Retrieve MongoDB URI from /etc/pritunl-web.env
  ansible.builtin.command:
    cmd: "grep 'PRITUNL_MONGODB_URI' /etc/pritunl-web.env"
  register: mongodb_uri_result

- name: Extract and set MongoDB URI
  set_fact:
    mongodb_uri: "{{ mongodb_uri_result.stdout | regex_replace('PRITUNL_MONGODB_URI=(.*)', '\\1') }}"

- name: Create backup directory if it does not exist
  ansible.builtin.file:
    path: "/backups"
    state: directory

- name: Perform MongoDB backup
  ansible.builtin.shell: "mongodump --uri=\"{{ mongodb_uri }}\" --archive=/backups/pritunl-backup-{{ actual_date }}.archive"
  register: backup_mongo

- name: Fetch the backup file from the source server
  ansible.builtin.fetch:
    src: "/backups/pritunl-backup-{{ actual_date }}.archive"
    dest: "/tmp/backups/"
    flat: yes
  delegate_to: "{{ ansible_host }}"

- name: Copy the backup to the destination server using SCP
  ansible.builtin.copy:
    src: "/tmp/backups/pritunl-backup-{{ actual_date }}.archive"
    dest: "/backups/"
    mode: '0644'
  delegate_to: "{{ destination_server }}"
