all:
  hosts:
    ub22srv01:
      ansible_host: 192.168.1.111
    ub22srv02:
      ansible_host: 192.168.1.112
    ub22srv03:
      ansible_host: 192.168.1.113
    ub22srv04:
      ansible_host: 192.168.1.114

  children:
    pritunl_blue_servers:
      hosts:
        ub22srv01:
        ub22srv03:

    pritunl_green_servers:
      hosts:
        ub22srv02:
        ub22srv04:

  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_timeout: 30
