---
# Add Pritunl GPG key and repository
- name: Add Pritunl GPG key
  ansible.builtin.apt_key:
    url: "{{ installation_pritunl_repo_pub }}"
    state: present

- name: Add Pritunl repository
  ansible.builtin.apt_repository:
    repo: "{{ installation_pritunl_repo_ubuntu }}"
    state: present

# Add MongoDB GPG key and repository
- name: Add MongoDB GPG key
  ansible.builtin.apt_key:
    url: "{{ installation_mongodb_repo_pub }}"
    state: present

- name: Add MongoDB repository
  ansible.builtin.apt_repository:
    repo: "{{ installation_mongodb_repo_ubuntu }}"
    state: present

# Update package cache
- name: Update package cache
  ansible.builtin.apt:
    update_cache: true

# Install required packages
- name: Install Pritunl, MongoDB, and WireGuard
  ansible.builtin.apt:
    name:
      - pritunl
      - mongodb-org
      - wireguard
      - wireguard-tools
    state: present

# Disable UFW
- name: Disable UFW
  community.general.ufw:
    state: disabled

# Enable and start services
- name: Enable and start MongoDB and Pritunl
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - mongod
    - pritunl
