---
# vars file for roles/installation
install_ub22_pritunl_repo_key: "https://raw.githubusercontent.com/pritunl/pgp/master/pritunl_repo_pub.asc"
install_ub22_pritunl_repo_url: "http://repo.pritunl.com/stable/apt"
install_ub22_pritunl_gpg_key_url: "https://raw.githubusercontent.com/pritunl/pgp/master/pritunl_repo_pub.asc"
install_ub22_mongodb_repo_key: "https://www.mongodb.org/static/pgp/server-6.0.asc"
install_ub22_mongodb_repo_url: "deb https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse"
install_ub22_mongodb_gpg_key_url: "https://www.mongodb.org/static/pgp/server-6.0.asc"
