---
# Ensure vm.max_map_count is set
- name: Ensure vm.max_map_count is set
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
    reload: true

# Create MongoDB directory
- name: Create MongoDB directory
  ansible.builtin.file:
    path: /mongodbfolder
    state: directory
    mode: "0750"

# Add Pritunl GPG key and repository
- name: Add Pritunl GPG key
  ansible.builtin.apt_key:
    url: "{{ install_ub22_pritunl_repo_key }}"
    state: present

- name: Add Pritunl repository
  ansible.builtin.apt_repository:
    repo: "deb {{ install_ub22_pritunl_repo_url }} jammy main"
    state: present

# Add MongoDB GPG key and repository
- name: Add MongoDB GPG key
  ansible.builtin.apt_key:
    url: "{{ install_ub22_mongodb_repo_key }}"
    state: present

- name: Add MongoDB repository
  ansible.builtin.apt_repository:
    repo: "{{ install_ub22_mongodb_repo_url }}"
    state: present

# Update package cache
- name: Update package cache
  ansible.builtin.apt:
    update_cache: true

# Install required packages
- name: Install Pritunl, MongoDB, and WireGuard
  ansible.builtin.apt:
    name:
      - pritunl
      - mongodb-org
      - wireguard
      - wireguard-tools
    state: present

# Disable UFW
- name: Disable UFW
  community.general.ufw:
    state: disabled

# Enable and start services
- name: Enable and start MongoDB and Pritunl
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - mongod
    - pritunl
