---
- name: Get sudo group information
  ansible.builtin.getent:
    database: group
    key: sudo
  register: sudo_group

- name: Ensure sudo group has members or define empty list
  set_fact:
    sudo_members: "{{ sudo_group.ansible_facts.getent_group.sudo[2].split(',') if sudo_group.ansible_facts.getent_group.sudo | length > 2 else [] }}"

- name: Debug sudo group members
  ansible.builtin.debug:
    var: sudo_members

- name: Check if 'edge' user is part of sudo group
  ansible.builtin.debug:
    msg: "Edge is not in sudo group. Triggering handler to add."
  when: "'edge' not in sudo_members"
  notify: add_edge_to_sudo
